# Generated by Django 3.2.2 on 2021-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='c'),
            preserve_default=False,
        ),
    ]
